### ISSUE TITLE
Viper as configuration library?

### ISSUE THREAD

**Issue by BimaPanduW** [typical-go/typical-rest-server#3]
Hi Mas @imantung 
I guess using https://github.com/kelseyhightower/envconfig as config management is not a good choice. The library is no longer maintained and has bad documentation. why not use viper instead?

**Comment by imantung** [comment]
The reason why I choose `envconfig` over `viper` because I want to keep configuration management simple by using the struct tag since this project only using environment variable as the source (I encourage to using [direnv](https://direnv.net/) for local machine).
